configuration:
  template_dir:
  - "mobans/templates"
  - ".moban.d"
  configuration: echarts-china-counties-pypkg.yml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - test.sh: test.script.jj2
  - "echarts_china_counties_pypkg/_version.py": "_version.py.jj2"
  - .gitignore: gitignore.jj2
  - .travis.yml: travis.yml.jj2
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: changelog.rst.jj2
